var CONSTANTS = {};

CONSTANTS.OBJECT_TYPE_GROUND = 0;
CONSTANTS.OBJECT_TYPE_PICKUP = 1;
CONSTANTS.OBJECT_TYPE_OBSTACLE = 2;


CONSTANTS.OBJECT_TYPE_GROUND_RECT = 0;
CONSTANTS.OBJECT_TYPE_GROUND_UP = 1;
CONSTANTS.OBJECT_TYPE_GROUND_DOWN = 2;

CONSTANTS.TILE_SIZE = 70;

module.exports = CONSTANTS;